name: Octo Organization CI

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: "File to check"
        default: "./data.txt"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: fast test
        run: |
          if [ ! -e "${{ github.event.inputs.file_name }}" ]; then
            exit 1
          fi
