name: Octo Organization CI

on:
  workflow_dispatch:
    file_name:
      name:
        description: "File to check"
        default: "./data.txt"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: fast test
        run: [ -e ${{ github.event.file_name.name }} ] || exit 1
