name: Quick Check file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    inputs:
      file_name:
        description: "File to check"
        default: "./data.txt"

    steps:
      - uses: actions/checkout@v4

      - name: fast test
        run: |
          if [ ! -e "${{ github.event.inputs.file_name }}" ]; then
            exit 1
          fi