name: Quick Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  quick_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: fast_test
        run: exit 0