name: Slow Check file

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  check_approve:
    if: github.event.review.state == 'APPROVED' && approved_by_team_member()
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      ORG_NAME: ${{ github.repository_owner }}
      GITHUB_REPO: ${{ github.event.repository.name }}
      YARO_TOKEN: ${{ secrets.YARO_TOKEN }}
      TEAM_NAME: yaro-team

    steps:
      - uses: actions/checkout@v4
      - name: initiate slow test
        id: init_slow_test
        run: |
          PR_USER=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $YARO_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$ORG_NAME/$GITHUB_REPO/pulls/$PR_NUMBER | jq -r .user.login)

          API_URL="https://api.github.com/orgs/$ORG_NAME/teams/$TEAM_NAME/members"
          TEAM_MEMBERS=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $YARO_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            $API_URL | jq -r '.[] | .login')
            
          for MEMBER in $TEAM_MEMBERS
          do
            if [ "$MEMBER" = "$PR_USER" ]
            then
              exit 0
            fi
          done
          exit 1

  slow_test:
    runs-on: ubuntu-latest
    needs: check_approve
    if: ${{ needs.check_approve.result == 'success' }}
    steps:
      - name: slow test
        run: exit 0


  functions:
    approved_by_team_member: |
      API_URL="https://api.github.com/orgs/$ORG_NAME/teams/$TEAM_NAME/members"
      TEAM_MEMBERS=$(curl -s -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $YARO_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        $API_URL | jq -r '.[] | .login')
      
      for MEMBER in $TEAM_MEMBERS; do
        if [ "$MEMBER" = "${{ github.event.review.user.login }}" ]; then
          exit 0  
        fi
      done
      
      exit 1
