name: Slow Check file

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  quick_test:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: fast test
        run: |
          if [ ! -e "./slow.txt" ]; then
            exit 1
          fi
