name: Slow Check

on:
  workflow_run:
    workflows: ["git_approval_check.yml"]
    types:
      - completed
  
  workflow_dispatch:

jobs:
  slow_test:
    needs: [check_approval]
    runs-on: ubuntu-latest
    steps:
      - name: slow test
        run: exit 0

        