name: Slow Check file

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  slow_test:
    if:  github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      ORG_NAME: ${{ github.repository_owner }}
      GITHUB_REPO: ${{ github.event.repository.name }}
      YARO_TOKEN: ${{ secrets.YARO_TOKEN }}
      ACTOR: ${{ github.actor }}
      TEAM_NAME: yaro-team


    steps:
      - uses: actions/checkout@v4
      - name: slow test
        id: test
        run: |
          API_URL="https://api.github.com/orgs/$ORG_NAME/teams/$TEAM_NAME/members"
          TEAM_MEMBERS=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" $API_URL | jq -r '.[] | .login')
          echo $TEAM_MEMBERS
  