name: Slow Checks

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  check_approval:
    if: ${{github.event.review.state == 'APPROVED'}}
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      ORG_NAME: ${{ github.repository_owner }}
      GITHUB_REPO: ${{ github.event.repository.name }}
      YARO_TOKEN: ${{ secrets.YARO_TOKEN }}
      TEAM_NAME: yaro-team

    steps:
      - uses: actions/checkout@v4
      - name: Check If it is Manual Run
        run: |

          if [ "${{ github.event_name }}" = 'workflow_dispatch' ]; then
            exit 0  
          fi

          API_URL="https://api.github.com/orgs/$ORG_NAME/teams/$TEAM_NAME/members"
          TEAM_MEMBERS=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $YARO_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            $API_URL | jq -r '.[] | .login')
          
          for MEMBER in $TEAM_MEMBERS; do
            if [ "$MEMBER" = "${{ github.event.review.user.login }}" ]; then
              exit 0  
            fi
          done
          
          exit 1

  slow_test:
    runs-on: ubuntu-latest
    steps:
      - name: slow test
        run: exit 0
        