name: Slow Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  slow_test:
    needs: [check_approval]
    runs-on: ubuntu-latest
    steps:
      - name: slow test
        run: exit 0

        