name: Slow Check file

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  slow_test:
    if:  github.event_name == 'pull_request_review' && github.event.review.state == 'APPROVED' && contains(github.event.pull_request.labels.*.name, 'bug')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Debugging output
        run: |
          echo "Review state: ${{ github.event.review.state }}"
          echo "Label name: ${{ github.event.label.name }}"

      - name: slow test
        run: exit 0
