name: Slow Check file

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  slow_test:
    if:  github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GITHUB_REPO: ${{ github.event.repository.name }}
      YARO_TOKEN: ${{ secrets.YARO_TOKEN }}

    steps:
      - uses: actions/checkout@v4


      - name: slow test
        id: test
        run: exit 0
      
      - name: Merge request
        if: steps.test.outcome == 'success'
        run: |
          API_URL="https://api.github.com/repos/$GITHUB_REPO/pulls/$PR_NUMBER/merge"
          RESPONSE=$(curl -s -X PUT -H "Authorization: token $YARO_TOKEN" -d '{"merge_method":"squash"}' $API_URL)
          echo "Response: $RESPONSE"