name: Slow Check file

on:
  pull_request:
    types: [labeled]


jobs:
  slow_test:
    if: ${{ github.event.label.name == 'your_label_name' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: slow test
        id: test
        run: exit 1